/**
 * Copyright IBM Corp. 2021, 2026
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktn get
export * as dataExternal from './data-external/index';
export * as provider from './provider/index';

